name: E2E Tests

on:
  push:
    branches:
      - units_piatachenko
  pull_request:
    branches:
      - sumdu.edu.ua
      - units_piatachenko

jobs:
  e2e-tests:
    runs-on: ubuntu-latest  # Use Linux environment

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 19
      - name: Set up Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      # Step 3: Install dependencies without running tests
      - name: Install dependencies without tests
        run: mvn install -DskipTests

      # Step 4: Package the JAR
      - name: Package the JAR
        run: mvn clean package

      # Step 5: Start the Javalin application from the JAR
      - name: Start Javalin Application
        run: java -jar target/universe-1.0-SNAPSHOT.jar --config=${{ github.workspace }}/application.properties &
        # Adjust the jar name as needed based on your actual JAR naming convention.

      # Step 6: Wait for the application to start
      - name: Wait for the application to start
        run: sleep 30

      # Step 7: Run Cucumber + Selenium tests
      - name: Run Cucumber + Selenium tests
        run: mvn test

      # Step 8: Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 9: Install dependencies for Robot Framework
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      # Step 10: Run Robot Framework E2E tests
      - name: Run Robot Framework E2E tests
        run: |
          robot --outputdir results e2e_tests/

      # Step 11: Archive test results
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            target/surefire-reports
            results/
