name: E2E Tests

on:
  push:
    branches:
      - units_piatachenko
  pull_request:
    branches:
      - sumdu.edu.ua
      - units_piatachenko

jobs:
  e2e-tests:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 19
      - name: Set up Java 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      # Step 3: Install dependencies without running tests
      - name: Install dependencies without tests
        run: mvn install -DskipTests

      # Step 4: Install Chrome (Ensure latest version)
      - name: Install Chrome
        run: choco install googlechrome --version=latest
        shell: cmd

      # Step 5: Install WebDriverManager (for managing ChromeDriver)
      - name: Install WebDriverManager dependencies
        run: mvn dependency:resolve

      # Step 6: Run the Java application
      - name: Run the Java application
        run: |
          mvn spring-boot:run &

      # Step 7: Run Selenium + Cucumber tests
      - name: Run Cucumber + Selenium tests
        run: |
          mvn test -Dselenium.chrome.options="--headless,--no-sandbox,--disable-dev-shm-usage"

      # Step 8: Set up Python for Robot Framework
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Robot Framework and dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install -r requirements.txt

      # Step 9: Run Robot Framework E2E tests
      - name: Run Robot Framework E2E tests
        run: |
          robot --outputdir results e2e_tests/

      # Step 10: Archive test results
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            target/surefire-reports
            results/
